Update to Datadog client 1.*
chaseconey/laravel-datadog-helper pull request #14
Opened 2019-07-08 07:14 UTC by barbushin

2019-07-31 15:13 UTC, jamesgraham commented
Any chance to get this approved+merged @chaseconey

2019-08-07 23:18 UTC, chaseconey requested changes
A couple of things:

- Let's re-add the `composer.lock`, should just need to re-run `composer update` and that will get the newest version of deps
- Please fix the formatting checks that are failing as per the status checks if you could (few simple things)

Once we knock those things out, I can spin up the old test project and we can release a new major version! Thank you for the contribution, this has been on my list for awhile 👍.

2019-08-07 23:18 UTC, chaseconey commented on .gitignore
> +composer.lock
Let's remove this

2019-08-07 23:22 UTC, chaseconey commented
Looks like we may need to downgrade our Travis setup to good ole' Trusty as well if we want to keep supporting PHP 5.4 [src](https://travis-ci.community/t/php-5-4-and-5-5-archives-missing/3723/4). I can do that separately, but that is why the Travis job is failing for 5.4.

2019-08-08 02:04 UTC, barbushin commented
@chaseconey No need to add composer.lock. It's library that depends from another library that could be updated also and the main thing is to keep backward compatibility.

2019-08-09 01:01 UTC, barbushin commented
> Please fix the formatting checks that are failing as per the status checks if you could (few simple things)

Done

2019-08-09 08:30 UTC, barbushin commented
All fixed

2019-08-09 21:40 UTC, chaseconey commented
@barbushin - I would like to keep the composer.lock in place in case, for whatever reason, a breaking change is introduced without a Major bump for underlying library. Been burned too many times by this.

2019-08-09 22:50 UTC, jamesgraham commented
> @barbushin - I would like to keep the composer.lock in place in case, for whatever reason, a breaking change is introduced without a Major bump for underlying library. Been burned too many times by this.

I agree with this sentiment

2019-08-13 02:16 UTC, merged